---
   - name: Install Metricbeat
     hosts: webservers
     become: true
     tasks:
       #Grab the .deb for Metricbeat
     - name: Download metricbeat
       command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
 
     - name: Install the .deb for metricbeat
       command: dpkg -i metricbeat-7.6.1-amd64.deb
 
     - name: Copy in the metricbeat.yml into Ansible config
       copy:
         src: /etc/ansible/metricbeat-config.yml
         dest: /etc/metricbeat/metricbeat.yml
 
     - name: Enable and Configure System Module (Ansible)
       command: metricbeat modules enable system
 
     - name: Run Metricbeat on Destination
       command: metricbeat setup
 
     - name: Start Metricbeat services
       command: systemctl start metricbeat
 
     - name: Enable service metricbeat on boot
       systemd:
         name: metricbeat
         enabled: yes

      #metricbeat-playbook.yml (filename)